In [1]:
import numpy as np


In [3]:
x=np.array([1,5,9,8])

In [4]:
print(x)

[1 5 9 8]


In [5]:
type(x)

numpy.ndarray

In [74]:
y=np.array([[1,2,3],[4,5,6]])
w=np.array([[7,8,9],[5,6,8]])

In [79]:
print(y*w)

[[ 7 16 27]
 [20 30 48]]


In [15]:
print(y[1])

[4 5 6]


In [16]:
print(y[0])

[1 2 3]


In [73]:
for i in y:
    print(i+3)

[4 5 6]
[7 8 9]


In [85]:
np.dtype(y)

TypeError: Cannot construct a dtype from an array

In [84]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.ones([1,1])

array([[1.]])

In [37]:
a=np.float_(2)
print(a)
type(a)

2.0


numpy.float64

In [31]:
b=np.int_([1,2,3])
b
type(b)

numpy.ndarray

In [41]:
z=np.arange(3,dtype=np.uint8)
z

array([0, 1, 2], dtype=uint8)

In [50]:
z=np.arange(10,dtype="f")
z

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [53]:
z.astype(int)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
np.int8(z)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int8)

In [65]:
d=np.dtype(complex)
d

dtype('complex128')

In [72]:
np.issubdtype(d,float)

False